# Generated by Django 5.0.6 on 2024-05-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='theclass',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='theclass',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
